#!/bin/zsh
[[ $# -eq 0 ]] && { echo Usage: $(basename $0) title >&2; exit 1 }

# #*. na eerste
# ##*. na laatste
# %.* voor laatste
# %%.* voor eerste

if [[ ${1##*.} == $1 ]]
then
  title=$1
  file=$1.html
else
  title=${1%.*}
  file=$1
fi

echo '<!DOCTYPE html>
<html lang="nl-NL">
	<head>
	<meta charset="utf-8" />
	<title>##TITLE##</title>
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
	<style>
		* { margin: 0; padding: 0; -webkit-user-select: none; }
		html, body { position: fixed; overflow: hidden; }
		main {perspective: 550px; width: 100%; height: 100%; position: fixed; }
</style>
</head>
<body>

<main></main>

<script></script>

</body>
</html>' | sed s/##TITLE##/$title/ > $file

open -a Atom $file
