#!/bin/zsh

[[ $# -eq 0 ]] && { echo Usage: $(basename $0) 'file project' >&2; exit 1 }

#

r=$RANDOM

# Arguments

file="$1"
	  [[ ! -f $file ]] && { "File not found: $file" >&2; exit 1 }
project="${(C)2}"
	  if [[ -z $project ]]
	  then
			 appiconset=~/Desktop/$r.appiconset
	  else
			 [[ ! -d ~/Developer/$project ]] && { "Project not found: $file" >&2; exit 1 }
			 appiconset=~/Developer/$project/$project/Assets.xcassets/AppIcon.appiconset
	  fi


# Vars

sizes=(20 29 40 58 60 76 80 87 120 152 167 180 1024)

#

	  echo

#

[[ ! -d $appiconset ]] && mkdir $appiconset
tmp=/tmp/$r.png

sips $file -Z $sizes[-1] --setProperty format png -o $tmp

for size in $sizes
do
	sips $tmp -Z $size -o $appiconset/$size.png
done

contentsjson='{
  "images" : [
    {
      "filename" : "40.png",
      "idiom" : "iphone",
      "scale" : "2x",
      "size" : "20x20"
    },
    {
      "filename" : "60.png",
      "idiom" : "iphone",
      "scale" : "3x",
      "size" : "20x20"
    },
    {
      "filename" : "58.png",
      "idiom" : "iphone",
      "scale" : "2x",
      "size" : "29x29"
    },
    {
      "filename" : "87.png",
      "idiom" : "iphone",
      "scale" : "3x",
      "size" : "29x29"
    },
    {
      "filename" : "80.png",
      "idiom" : "iphone",
      "scale" : "2x",
      "size" : "40x40"
    },
    {
      "filename" : "120.png",
      "idiom" : "iphone",
      "scale" : "3x",
      "size" : "40x40"
    },
    {
      "filename" : "120.png",
      "idiom" : "iphone",
      "scale" : "2x",
      "size" : "60x60"
    },
    {
      "filename" : "180.png",
      "idiom" : "iphone",
      "scale" : "3x",
      "size" : "60x60"
    },
    {
      "filename" : "20.png",
      "idiom" : "ipad",
      "scale" : "1x",
      "size" : "20x20"
    },
    {
      "filename" : "40.png",
      "idiom" : "ipad",
      "scale" : "2x",
      "size" : "20x20"
    },
    {
      "filename" : "29.png",
      "idiom" : "ipad",
      "scale" : "1x",
      "size" : "29x29"
    },
    {
      "filename" : "58.png",
      "idiom" : "ipad",
      "scale" : "2x",
      "size" : "29x29"
    },
    {
      "filename" : "40.png",
      "idiom" : "ipad",
      "scale" : "1x",
      "size" : "40x40"
    },
    {
      "filename" : "80.png",
      "idiom" : "ipad",
      "scale" : "2x",
      "size" : "40x40"
    },
    {
      "filename" : "76.png",
      "idiom" : "ipad",
      "scale" : "1x",
      "size" : "76x76"
    },
    {
      "filename" : "152.png",
      "idiom" : "ipad",
      "scale" : "2x",
      "size" : "76x76"
    },
    {
      "filename" : "167.png",
      "idiom" : "ipad",
      "scale" : "2x",
      "size" : "83.5x83.5"
    },
    {
      "filename" : "1024.png",
      "idiom" : "ios-marketing",
      "scale" : "1x",
      "size" : "1024x1024"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
'

# contentsjson='{
#   "images" : [
#     {
#       "filename" : "16.png",
#       "idiom" : "mac",
#       "scale" : "1x",
#       "size" : "16x16"
#     },
#     {
#       "filename" : "32.png",
#       "idiom" : "mac",
#       "scale" : "2x",
#       "size" : "16x16"
#     },
#     {
#       "filename" : "32.png",
#       "idiom" : "mac",
#       "scale" : "1x",
#       "size" : "32x32"
#     },
#     {
#       "filename" : "64.png",
#       "idiom" : "mac",
#       "scale" : "2x",
#       "size" : "32x32"
#     },
#     {
#       "filename" : "128.png",
#       "idiom" : "mac",
#       "scale" : "1x",
#       "size" : "128x128"
#     },
#     {
#       "filename" : "256.png",
#       "idiom" : "mac",
#       "scale" : "2x",
#       "size" : "128x128"
#     },
#     {
#       "filename" : "256.png",
#       "idiom" : "mac",
#       "scale" : "1x",
#       "size" : "256x256"
#     },
#     {
#       "filename" : "512.png",
#       "idiom" : "mac",
#       "scale" : "2x",
#       "size" : "256x256"
#     },
#     {
#       "filename" : "512.png",
#       "idiom" : "mac",
#       "scale" : "1x",
#       "size" : "512x512"
#     },
#     {
#       "filename" : "1024.png",
#       "idiom" : "mac",
#       "scale" : "2x",
#       "size" : "512x512"
#     }
#   ],
#   "info" : {
#     "author" : "xcode",
#     "version" : 1
#   }
# }
# '

<<< $contentsjson > $appiconset/Contents.json

echo

read '?Open folder? '; open $appiconset

echo
